on: [push]

jobs:
  cflint_test_job:
    runs-on: self-hosted
    name: A job to test CFLint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fabianrolf/cflint-action
          path: action-src
      - name: CFLint
        uses: ./action-src/
        id: cflint-action
      - name: Upload Lint Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}/lint