on: [push]

jobs:
  cflint_test_job:
    runs-on: self-hosted
    name: A job to test CFLint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fabianrolf/cflint-action
          ref: master
      - name: CFLint
        uses: ./
        id: cflint-action